export const addressConstants = {

    GET_USER_ADDRESSES_REQUEST: "GET_USER_ADDRESSES_REQUEST",
    GET_USER_ADDRESSES_SUCCESS: "GET_USER_ADDRESSES_SUCCESS",
    GET_USER_ADDRESSES_FAILURE: "GET_USER_ADDRESSES_FAILURE",

    NEW_ADDRESS_REQUEST: 'NEW_ADDRESS_REQUEST',
    NEW_ADDRESS_SUCCESS: 'NEW_ADDRESS_SUCCESS',
    NEW_ADDRESS_FAILURE: 'NEW_ADDRESS_FAILURE',

    SEARCH_ADDRESS_REQUEST: 'SEARCH_ADDRESS_REQUEST',
    SEARCH_ADDRESS_CLEAR: 'SEARCH_ADDRESS_CLEAR',
    SEARCH_ADDRESS_SUCCESS: 'SEARCH_ADDRESS_SUCCESS',
    SEARCH_ADDRESS_FAILURE: 'SEARCH_ADDRESS_FAILURE',

    EDIT_ADDRESS_REQUEST: 'EDIT_ADDRESS_REQUEST',
    EDIT_ADDRESS_SUCCESS: 'EDIT_ADDRESS_SUCCESS',
    EDIT_ADDRESS_FAILURE: 'EDIT_ADDRESS_FAILURE',

    DELETE_ADDRESS_REQUEST: 'DELETE_ADDRESS_REQUEST',
    DELETE_ADDRESS_SUCCESS: 'DELETE_ADDRESS_SUCCESS',
    DELETE_ADDRESS_FAILURE: 'DELETE_ADDRESS_FAILURE',
};
