export const orderConstant = {

    GET_PRODUCT_ORDER_REQUEST: "  GET_PRODUCT_ORDER_REQUEST",
    GET_PRODUCT_ORDER_SUCCESS: "  GET_PRODUCT_ORDER_SUCCESS",
    GET_PRODUCT_ORDER_FAILURE: "  GET_PRODUCT_ORDER_FAILURE",
  
    
    
  };
  