export const orderConstant = {

    GET_PRODUCT_ORDER_REQUEST: "  GET_PRODUCT_ORDER_REQUEST",
    GET_PRODUCT_ORDER_SUCCESS: "  GET_PRODUCT_ORDER_SUCCESS",
    GET_PRODUCT_ORDER_FAILURE: "  GET_PRODUCT_ORDER_FAILURE",
  
    GET_INLINE_ORDERS_REQUEST: "  GET_INLINE_ORDERS_REQUEST",
    GET_INLINE_ORDERS_SUCCESS: "  GET_INLINE_ORDERS_SUCCESS",
    GET_INLINE_ORDERS_FAILURE: "  GET_INLINE_ORDERS_FAILURE",
  
    
    
  };
  