export const orderConstant = {

  GET_PRODUCT_ORDER_REQUEST: "  GET_PRODUCT_ORDER_REQUEST",
  GET_PRODUCT_ORDER_SUCCESS: "  GET_PRODUCT_ORDER_SUCCESS",
  GET_PRODUCT_ORDER_FAILURE: "  GET_PRODUCT_ORDER_FAILURE",

  GET_ORDER_PRODUCTS_TYPES_REQUEST: "GET_ORDER_PRODUCTS_TYPES_REQUEST",
  GET_ORDER_PRODUCTS_TYPES_SUCCESS: "GET_ORDER_PRODUCTS_TYPES_SUCCESS",
  GET_ORDER_PRODUCTS_TYPES_FAILURE: "GET_ORDER_PRODUCTS_TYPES_FAILURE",

  GET_INLINE_ORDERS_REQUEST: "GET_INLINE_ORDERS_REQUEST",
  GET_INLINE_ORDERS_SUCCESS: "GET_INLINE_ORDERS_SUCCESS",
  GET_INLINE_ORDERS_FAILURE: "GET_INLINE_ORDERS_FAILURE",

  GET_ORDER_DETAILS_REQUEST: "GET_ORDER_DETAILS_REQUEST",
  GET_ORDER_DETAILS_SUCCESS: "GET_ORDER_DETAILS_SUCCESS",
  GET_ORDER_DETAILS_FAILURE: "GET_ORDER_DETAILS_FAILURE",

  CANCEL_ORDER_REQUEST: "CANCEL_ORDER_REQUEST",
  CANCEL_ORDER_SUCCESS: "CANCEL_ORDER_SUCCESS",
  CANCEL_ORDER_FAILURE: "CANCEL_ORDER_FAILURE",

  ADD_ORDER_REQUEST: "ADD_ORDER_REQUEST",
  ADD_ORDER_SUCCESS: "ADD_ORDER_SUCCESS",
  ADD_ORDER_FAILURE: "ADD_ORDER_FAILURE",

  GET_FINISHED_ORDERS_REQUEST: "GET_FINISHED_ORDERS_REQUEST",
  GET_FINISHED_ORDERS_SUCCESS: "GET_FINISHED_ORDERS_SUCCESS",
  GET_FINISHED_ORDERS_FAILURE: "GET_FINISHED_ORDERS_FAILURE",

};
