export const userConstants = {
    
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    VERIFICATION_CODE_REQUEST: 'VERIFICATION_CODE_REQUEST',
    VERIFICATION_CODE_SUCCESS: 'VERIFICATION_CODE_SUCCESS',
    VERIFICATION_CODE_FAILURE: 'VERIFICATION_CODE_FAILURE'
    
};
